version: 2.1

jobs:
  test:
    working_directory: ~/repo
    docker:
    - image: cimg/node:20.5.1
    steps:
      - checkout # git clone del codigo
      - restore_cache: # cunado se ejecuta el restore busca la cache si se ha cambiado la primera vez falla
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install
      - run:
          name: Run lint
          command: npm run lint:report
      - run:
          name: Run tests
          command: npm run test:coverage      
      - store_test_results:
          path: test-results.xml

      - save_cache: 
          paths:
            - node_modules # Guarda esta carpeta
          key: v1-dependencies-{{ checksum "package.json" }} # v1-depe y el checksum -> identificador de un fichero. cuando cambia "package,json" la cache queda invalidada

workflows:
  test-deploy:
    jobs:
      - test
